#!/bin/bash



echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mWWNNXK0OOO0KNW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMM\e[0\e[34mNX0Okxxdooooddddl',llcoK\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMM\e[0\e[34mWKd:;coldO0KXXNWWWWk;oK0x:ckN\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMM\e[0\e[34mXd;..;kK0OKXK0Okxxdol;,o0NNkcoX\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMM\e[0\e[34mNo,''..:llldxddddxxkO0Kx:lXMMKocOW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMM\e[0\e[34mNo'..,:lx0NW\e[0m\e[37mMMMMMMMMMMM\e[0m\e[34mWKocOWMNxcxX\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMM\e[0\e[34mWKd,...,dXW\e[0m\e[37mMMMMMMMMMMMMMMMM\e[0m\e[34mNxcxNMW0clKW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMM\e[0\e[34mW0;.':l;..cK\e[0m\e[37mMMMMMMMMMMMMMMMMM\e[0m\e[34mW0ll0WNO:;kW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMM\e[0\e[34mWd.'xWWK:.;0\e[0m\e[37mMMMMMMMMMMMMMMMMMMM\e[0m\e[34mXdcdl;;';OW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMM\e[0\e[34mWo.;0MMWd.,OW\e[0m\e[37mMMMMMMMMMMMMMMMMMMM\e[0m\e[34mWx',;,,;c0\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMM\e[0\e[34mWd.;OKkc,.,OW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMM\e[0m\e[34mO,.,,,'.dW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMM\e[0\e[34mWWWMWk'..:c...:K\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMM\e[0m\e[34m0,......dW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMM\e[0\e[34mNKKkl:dNWW0:..cc..:K\e[0m\e[37mMMMMMMMMMMMMMMMMMMMM\e[0m\e[34mW0,......dW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m M\e[0\e[34mWO:';l'..xWMWO,.'o:..oN\e[0m\e[37mMMMMMMMMMMMMMMMMMMMM\e[0m\e[34mO,......oW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MM\e[0\e[34mXc..cl..;0MMNd..,c'..dW\e[0m\e[37mMMMMMMMMMMMMMMMMMMM\e[0m\e[34mO'......oW\e[0m\e[37mMMMMMMMMMMMMMMMM\e[0m\e[34mWWWNWWW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMM\e[0\e[34m0;..l:..cXMMXc..:l..,0\e[0m\e[37mMMMMMMMMMMMMMMMMMM\e[0m\e[34mWd...;;..:0W\e[0m\e[37mMMMMMMMMMMMM\e[0m\e[34mW0oc:;;;:ldON\e[0m\e[37mMMMMMMM\e[0m\e[34mWOlllllllloox0N\e[0m\e[37mMMMMMMMM \e[0m"
echo -e "\e[37m MMM\e[0\e[34mWx..'l,..l0kd:..,d;..xW\e[0m\e[37mMMMMMMMMMMMMMMMM\e[0m\e[34mNx'.'lloc..;ONW\e[0m\e[37mMMMMMMMMMM\e[0m\e[34mWx,,,,,,,'..c0W\e[0m\e[37mMMMMM\e[0m\e[34mWo...''''''...:kN\e[0m\e[37mMMMMMM \e[0m"
echo -e "\e[37m MMMM\e[0\e[34mNo..;o,......,;c:..,0\e[0m\e[37mMMMMMMMMMMMMMMMM\e[0m\e[34mNd..'l:..cc..,ckW\e[0m\e[37mMMMMMMMMM\e[0m\e[34mWO:,'''',cc..;0\e[0m\e[37mMMMMM\e[0m\e[34mWo..;l:;;;:c:'..oN\e[0m\e[37mMMMMM \e[0m"
echo -e "\e[37m MMMMM\e[0\e[34mXc..;c;,;::;;,...:OW\e[0m\e[37mMMMMMMMMMMMMMMM\e[0m\e[34mNo..,l;....cl...,kW\e[0m\e[37mMMMMMMMM\e[0m\e[34mWd';clc..'o:..x\e[0m\e[37mMMMMM\e[0m\e[34mWl..;:......:o,.'O\e[0m\e[37mMMMMM \e[0m"
echo -e "\e[37m MMMMMM\e[0\e[34mKl...','....,cdON\e[0m\e[37mMMMMMMMMMMMMMMMM\e[0m\e[34mXl..,l,..;,..:c...'xN\e[0m\e[37mMMMMMMMM\e[0m\e[34mXKNWO:..:l'.,O\e[0m\e[37mMMMMM\e[0m\e[34mWo..;c...,..,d;.'k\e[0m\e[37mMMMMM \e[0m"
echo -e "\e[37m MMMMMMM\e[0\e[34mW0xoc:cldk0XW\e[0m\e[37mMMMMMMMMMMMMMMMMMM\e[0m\e[34mXl..;l,..oXKc..:lc,.'xN\e[0m\e[37mMMMMMMMMM\e[0m\e[34mNx,..cc...lX\e[0m\e[37mMMMMM\e[0m\e[34mWo..;c.....'lc..;K\e[0m\e[37mMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mK:..;l,..lKNN0:..;oc'..oX\e[0m\e[37mMMMMMMM\e[0m\e[34mKl..,c;....'xW\e[0m\e[37mMMMM\e[0m\e[34mWo..;c..',..:l'..oX\e[0m\e[37mMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mW0:..:l'.'c:,,,;c:...;l,..oN\e[0m\e[37mMMMM\e[0m\e[34mWk;..'lc;,,,,;kW\e[0m\e[37mMMMM\e[0m\e[34mWo..;c..cO:..;l,..cK\e[0m\e[37mMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mWO;..:c'.'xNO:..cKXl...;l,..lK\e[0m\e[37mMM\e[0m\e[34mXd.............xW\e[0m\e[37mMMMM\e[0m\e[34mWo..;c..lNXo..,l:..;OW\e[0m\e[37mM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mWOoox0xooOW\e[0m\e[37mMMXkONMM\e[0m\e[34mXxoookOdodKWXl''',ldxxxo;..'oX\e[0m\e[37mMMMM\e[0m\e[34mWKxxO0xx0W\e[0m\e[37mM\e[0m\e[34mNOxxOKkxx0W\e[0m\e[37mM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mWk:;,,;oX\e[0m\e[37mMM\e[0m\e[34mWO:;,,;dN\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34m0l;,;ckW\e[0m\e[37mMM\e[0m\e[34mW0c;',:kN\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[0\e[34mWX000XW\e[0m\e[37mMMMM\e[0m\e[34mWKkdkKW\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo -e "\e[37m MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\e[7;4;36mUNIVERSITY OF ANTOFAGASTA ROBOTICS RESEARCH\e[0m\e[37mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM \e[0m"
echo
#version="$(lsb_release -sc)"

## nombre del paquete
   nameSetup1="UGV SIMULATION"
##
echo -e "\e[1;31mpackage $nameSetup1 \e[0m"
echo

## nombre del launch
   name1Comp1="lalcktur"
##
echo -e "̣\e[7;33m $name1Comp1 of $nameSetup1 \e[31m "
echo "choose fidelity"
echo "1 = normal"
echo "2 = medium"
echo "3 = low"
read fidelity

##? se lanza segun calidad
   if [ $fidelity == "1" ]
	then
	   echo -e "\e[7;35m launching NORMAL FIDELITY $name1Comp1 of $nameSetup1 \e[0m"
      echo -e "\e[7;31m <<\e[7;31m"  
      roslaunch ugv_simulator lalcktur.launch 
	   echo -e " \e[7;31m" 
   elif [ $fidelity == "2" ]
   then
      echo -e "\e[7;35m launching MEDIUM FIDELITY $name1Comp1 of $nameSetup1\e[0m"
      echo -e "\e[7;31m <<\e[7;31m"  
      roslaunch ugv_simulator lalcktur.launch world:=lalckturv2_2Midfi
	   echo -e " \e[7;31m" 
   elif [ $fidelity == "3" ]
   then
      echo -e "\e[7;35m launching LOW FIDELITY $name1Comp1 of $nameSetup1 \e[0m"
      echo -e "\e[7;31m <<\e[7;31m"  
      roslaunch ugv_simulator lalcktur.launch world:=lalckturv2_2Lowfi
	   echo -e " \e[7;31m" 
	else
	   echo -e "\e[7;35m valor no correcto\e[0m" 
	   echo -e " \e[7;31m"
      exit
   fi
##?